### PR TITLE
mod for Windows compatibility, removal of unnecessary newlines and addition of model-name prefix 

### PR DESCRIPTION
**Pull request by Brentgreenwood**
Proposed changes included:
1. changed subprocess call to explicitly call powershell on Windows machines (CMD failing to parse correctly)
2. removed unnecessary newlines being added during write file
3. added optional param for table-name prefixing with source-name to avoid name collisions in staging layer

### CODE REVIEW

**Comment by tuanchris** [comment]
Hi @Brentgreenwood, thanks for the contribution! Since I don't have access to a Windows machine, can you help provide a screenshot showing this is running fine?

**Comment by Brentgreenwood** [comment]
Hi @tuanchris - Yes, for sure.  generate_base_model call is working as expected on Win10.  I'll run thru the other 2 function calls this weekend on Win10, as well as all 3 on my Mac this weekend and post results here.

**Comment by Brentgreenwood** [comment]
Tested both generate and process paths.  Ran into some empty line issues with processing transforms, so made some minor changes there to handle empty lines.  And added 2 additional tests to make sure the line spacing was added back correctly on the write_file call.
dbt_gen_pytest_result
dbt_gen_pycharm_x2_test
Testing on Mac now and will post results momentarily.

**Comment by Brentgreenwood** [comment]
tests successful on MacOS as well. Let me know if these changes are helpful.

Screen Shot 2021-11-07 at 7 17 30 PM
Screen Shot 2021-11-08 at 9 55 29 AM

**Comment by tuanchris** [comment]
@Brentgreenwood LGTM. Thanks for the contribution!

**Pull request merged**
